language: generic
#os: osx
matrix:
  include:
    - os: linux
      dist: trusty
      env: COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5
      addons:
        apt:
          packages:
            - g++-5
            - pkg-config
            - libglm-dev
            - libyaml-cpp0.3
            - liblo-dev
            - xorg-dev
            - xserver-xorg-dev-lts-trusty
          sources: &sources
            - llvm-toolchain-precise-3.8
            - ubuntu-toolchain-r-test
#    - os: linux
#      dist: trusty
#      env: COMPILER_NAME=clang CXX=clang++-3.8 CC=clang-3.8
#      addons:
#        apt:
#          packages:
#            - g++-5
#            - clang-3.8
#          sources: *sources

install: 
    - ./travis/scripts/install_glfw3
    - ./travis/scripts/install_glbinding              

script: 
    - mkdir build && cd build
    - cmake .. && make
