language: generic
os: 
  - linux
  - osx
dist: trusty
osx_image:
  - xcode8.2
  - xcode7.3
env:
  - COMPILER_NAME=gcc CXX=g++-5 CC=gcc-5 PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR/travis/tmp/local/lib/pkgconfig CMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/travis/tmp/local
  - COMPILER_NAME=clang-3.8 CXX=clang++-3.8 CC=clang-3.8 PKG_CONFIG_PATH=$TRAVIS_BUILD_DIR/travis/tmp/local/lib/pkgconfig CMAKE_PREFIX_PATH=$TRAVIS_BUILD_DIR/travis/tmp/local
addons:
  apt:
    packages:
      - g++-5
      - clang-3.8
      - pkg-config
      - xorg-dev
      - libfreeimage-dev
    sources: &sources
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
install: 
    - ./travis/scripts/install_glbinding              
    - ./travis/scripts/install_glfw3
    - ./travis/scripts/install_glm
    - ./travis/scripts/install_liblo
    - ./travis/scripts/install_yaml_cpp

script: 
    - mkdir build && cd build
    - cmake .. && make
