#!/bin/bash

mkdir -p travis/tmp
cd travis/tmp

git clone https://github.com/glfw/glfw

cd glfw 

git fetch origin latest
git checkout latest

mkdir build && cd build

cmake -DCMAKE_INSTALL_PREFIX=../../local ..
make install
