#!/bin/bash

mkdir travis/tmp
cd travis/tmp

mkdir install

git clone https://github.com/radarsat1/liblo

cd liblo

mkdir cmake-build && cd cmake-build

cmake -DCMAKE_INSTALL_PREFIX=../../local ../cmake
make install
