#!/bin/bash

mkdir -p travis/tmp
cd travis/tmp

git clone https://github.com/jbeder/yaml-cpp

cd yaml-cpp 

mkdir build && cd build

cmake -DCMAKE_INSTALL_PREFIX=../../local -DCMAKE_CXX_FLAGS=-fPIC ..
make install
