#!/bin/bash

mkdir travis/tmp
cd travis/tmp

mkdir install

git clone https://github.com/jbeder/yaml-cpp

cd yaml-cpp 

git fetch --tags
git checkout release-0.5.3

mkdir build && cd build

cmake -DCMAKE_INSTALL_PREFIX=../../local ..
make install
