defaults:
  background: [0, 0, 0, 1]

elements:
  domainwarp:
    type: Shader
    fragment: elements/domainwarp.fsh
    uniforms:
      lacunarity: lacunarity
      H: H
    defaults:
      lacunarity: 2
      H: 0.26

order: [domainwarp]
