output:
  enabled: false
  name: /dev/video1
  width:  1440
  height: 900

elements:
  lines1:
    type: Line
    defaults:
      width/base: [10]
      distance/base: [0.1]
      distance/amplitude: [0.0]
      distance/omega: [0.0]
      distance/lambda: [0.0]
      color/base: [1.0, 0.5, 0.5, 1.0]
      color/amplitude: [0.0, 0.1, -0.1, 0.0]
      color/omega: [0.0]
      color/lambda: [0.0]
  lines2:
    type: Line
    defaults:
      angle: [1.57079632679489661922]
      width/base: [10]
      distance/base: [0.08]
      distance/amplitude: [0.05]
      distance/omega: [1]
      distance/lambda: [.1]
      color/base: [0.0, 0.0, 0.0, 0.0]
      color/amplitude: [0.0, 0.0, 0.0, 0.0]
      color/omega: [1.0]

order: [lines1, lines2]
