defaults:
  background: [0, 0, 0, 0.2]

output:
  enabled: false
  name: /dev/video1
  width:  600
  height: 600

# input:
#   mouse:
#     xy:
#       - particles/center

elements:
  particles:
    type: Particles

order: [particles]
