defaults:
  background: [0, 0, 0, 1]

elements:
  truchet:
    type: Shader
    fragment: elements/truchet.fsh
    uniforms:
      glow: glow
      freq: freq
    defaults:
      glow: 0.0
      freq: 1.0

order: [truchet]
