paths:
  shaders: resources/shaders

network:
  port: 6666

window:
  vsync: true
  cursor: false
  fullscreen: true
  multisampling: 1
  title: Études audiovisuels

viewport:
  width: 1440
  height: 900
  scaling: border

logging:
  logLevel: debug
  framerate: false

scenes:
  - spiral
  - multifractal
  - domainwarp
  - truchet
  # - testbed
  # - parallels
  # - grid
  # - particles
  # - space
  # - algosynth
  # - sinusoids
  # - ca
  # - shader
  # - flowtrace
